
export const metadata = {
      title: "My Shop",
      description: "Generated by create next app",
    };




export default function ({ children }) {
    return (
        <div>
            <h1>Shop Layout</h1>
            {children}
        </div>
    )
}