'use client';
import { Poppins } from "next/font/google";
import { usePathname } from "next/navigation";


// import "./globals.css";



const poppins = Poppins({
  subsets: ['latin'],
  weight: '400',
})

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const pathname = usePathname();

  console.log("pathname", pathname);

  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        {pathname.indexOf("/shop") == -1 && <h1>Header</h1>}

        {children}
      </body>
    </html>
  );
}
